#pragma once
#include <array>
//simply listing out standard entries able for use.
constexpr unsigned short sESize(95);

constexpr std::array<const char*, sESize> standard_entries{ // using string would implicitally convert it from const char*, making it not constexpr.

	"The next time I see a pet or animal",
	"The next time look at my face in a mirror",
	"The next time turn on a light",
	"The next time see a flower",
	"The next time write anything down",
	"The next time feel pain",
	"The next time I hear someone say my name",
	"The next time I drink something",
	"The next time I see a traffic light",
	"The next time I hear music",
	"The next time I throw something in the garbage",
	"The next time I hear laughter",
	"The next time I turn on a television or radio",
	"The next time I see a vegetable",
	"The next time I see a red car",
	"The next time I handle money",
	"The next time I read something other than this list",
	"The next time I check the time",
	"The next time I notice myself daydreaming",
	"The next time I hear the telephone ringing",
	"The next time I open a door",
	"The next time I see a bird",
	"The next time I use the toilet after noon",
	"The next time I see the stars",
	"The next time I put a key in a lock",
	"The next time I see an advertisement",
	"The next time I eat anything after breakfast",
	"The next time I see a bicycle",
	"Spotting someone with a corf",
	"Spotting someone with gloves",
	"Spotting someone with a hat",
	"Spotting someone with a purse/bag/suitcase",
	"Spotting someone with a tie",
	"Hearing the words hello, goodbye and any variations",
	"Hearing or reading a word in a foreign language",
	"Hearing the words \"I'm sorry, wait, okay and any variations\"",
	"Spotting a motocycle or a bycicle",
	"Spotting someone (including yourself) yawn or frown",
	"Spotting someone (including yourself) laugh or smile",
	"Spotting someone (including yourself) complimenting someone (with gestures or a hand-shake)",
	"Spotting an attractive female/male",
	"Spotting a very elderly male/female or a crippled person",
	"Spotting a baby or a very young child",
	"Openning any fridge, drawer or closet",
	"Entering in any elevator",
	"Climbing any stairs or ramps",
	"Spotting someone grab their wallet (including yourself)",
	"Grabbing food",
	"Grabbing any piece of clothing (including removing and placing it in somewhere)",
	"Spotting someone (including yourself) picking their keys",
	"Spotting a reference to a recent movie or book",
	"Spotting a commercial ad related to food",
	"Spotting a comercial ad related to clothing and cosmetics",
	"Spotting any reference to medicine pills",
	"Hearing someone (including yourself) engaging in a sexual/erotic topic",
	"Spotting someone (including yourself) visibly worried or stressed",
	"Spotting someone (including yourself) visibly happy or exuberant",
	"Recalling a very negative moment that happened recently or in the far past",
	"Recalling a very positive moment that happened recently or in the far past",
	"Touching in an animal (including human beings) or plant",
	"Spotting a comercial ad about cars",
	"Feeling yourself ansious about something (either good or bad)",
	"Meeting a known but not too close person",
	"Experiencing a weird situation or scenario",
	"Observing a situation of injustice (towards you or others)",
	"Observing a situation of violence",
	"Observing or enganging in a discussion",
	"Reading/watching/hearing a reference to a supernatural concept",
	"Reading/watching/hearing a reference to dreaming or the brain",
	"Feeling noticeably pain or pleasure",
	"Feeling noticeably cold or hot",
	"Spotting a bug",
	"Spotting/using a trash can",
	"Grabbing paper towell",
	"Engaging in personal higiene",
	"Noticing your forgot something recently",
	"Making a mental note for the recent future",
	"Leaving/entering in a building or in a vehicle",
	"Spotting someone (including yourself) sneezing or spitting to the ground",
	"Turning your computer on/off, or leaving it inactive for more than a few minutes",
	"Feeling sexually aroused",
	"Inserting your username/password on a website",
	"Opening google,facebook,twitter or youtube",
	"Spotting any internet publicity about a virtual game",
	"Leaving/arriving at home or work",
	"Crossing a street crosswalk",
	"Watching a movie trailer",
	"Watching a educational video",
	"Reading a scientifical article",
	"Waitting at a bus stop",
	"Lying to someone",
	"Make a nice action towards someone you don't know",
	"Hearing someone (including yourself) mentioning the weather",
	"Spotting someone (including yourself) picking or dropping an object",
	"Making a question to someone or to yourself",
};
